apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: kafka-operator
manifests:
  rawYaml:
  - manifests/kafka-operator.yaml
deploy:
  kubectl: 
    flags:
      global: # additional flags passed on every command.
      - --namespace=kafka
    hooks:
      before: 
        - host:
            command: ["sh", "-c", "./get-manifests.sh"]
            os: [darwin, linux]

